title: Wrye-Code-Collection Wiki
description: Collection of Wrye Bash history and information
exclude: [
  '_pagebuilder/',
  '.idea/**',
]
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
