title: Wrye-Code-Collection Wiki
description: Collection of Wrye Bash history and information
exclude: [
  'pagebuilder/',
  '_sass/src/',
  '_sass/Old CSS/',
  '.idea/',
]
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
