C:\Python38-32\python.exe wtxt-wiki.py genHtml index.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 2-wryebashfeatures.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 3-wryemashusage.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 4-generalusage.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 5-advancedusage.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 6-technicalreferences.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 7-tomeofpsymon.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 8-tomeofalt3rn1ty.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 9-morrowindandbeyond.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 10-contribute.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 11-tutorial_Links.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 12-other_tools_and_extras.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 13-oblivionandbeyond.txt
C:\Python38-32\python.exe wtxt-wiki.py genHtml 14-testoolghostwheel.txt
